services:
  app:
    image: ghcr.io/mord0rek/directory-listing:latest
    user: "1000:1000"
    ports:
      - "8080:80"
    volumes:
      - ./Pliki:/var/www/html/content
      - ./ikony:/var/www/html/assets/icons/custom
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      WEBHOOK_TOKEN: "super-tajny-sekret"
